### ISSUE TITLE
multi_particle_fit_test.Rmd not rendering

### ISSUE THREAD

**Issue by urbach** [HISKP-LQCD/hadron#222]
its not rendering for me

    label: unnamed-chunk-11
    Quitting from lines 142-156 (multi_particle_fit_test.Rmd) 
    Error in rbind(gr(par = par, x = x, ...), grpriors) : 
      number of columns of matrices must match (see arg 2)

**Comment by urbach** [comment]
This leads Travis check to fail, I think...

**Comment by kostrzewa** [comment]
No, the travis check fail is due to problems with biber which I've seen before on the HISKP institute machines when the version of biber was manually fixed by someone to a specific version:

```
add of symlinks had 1 error(s), see messages above.

INFO - This is Biber 2.14

INFO - Logfile is 'hankel.blg'

INFO - Reading 'hankel.bcf'

ERROR - Error: Found biblatex control file version 3.3, expected version 3.7.

This means that your biber (2.14) and biblatex (3.7) versions are incompatible.

See compat matrix in biblatex or biber PDF documentation.

INFO - ERRORS: 1

Warning: LaTeX Warning: Citation 'prony:1795' on page 1 undefined on input line 154.

LaTeX Warning: Citation 'Lin:2007iq' on page 1 undefined on input line 154.

LaTeX Warning: Citation 'gardner:1959' on page 1 undefined on input line 155.

LaTeX Warning: Empty bibliography on input line 357.

Package rerunfilecheck Warning: File `hankel.out' has changed.

(rerunfilecheck)                Rerun to get outlines right

(rerunfilecheck)                or use package `bookmark'.

LaTeX Warning: There were undefined references.

LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.

Package biblatex Warning: Please (re)run Biber on the file:

(biblatex)                hankel

(biblatex)                and rerun LaTeX afterwards.

Error: processing vignette 'hankel.Rmd' failed with diagnostics:

Failed to build the bibliography via biber

--- failed re-building ‘hankel.Rmd
```

**Comment by martin-ueding** [comment]
That is another issue. But I was actually missing something in a list. And if you do `higher_states$ampl` and it is not there, you get `NULL`. And `c(x, NULL)` just gives `x` without an error or warning. This is now fixed and the biber issue remains.

**Comment by kostrzewa** [comment]
AFAIU, we need to use `before_install` in `.travis.yml` to set up the texlive environment with everything that is actually required for rendering all the vignettes that we have. Otherwise, it will attempt to download things as required and this seems to result in incompatible versions being installed.

**Comment by kostrzewa** [comment]
See also https://docs.travis-ci.com/user/languages/r/#latextexlive-packages

**Comment by kostrzewa** [comment]
https://yihui.org/tinytex/ is installed with the `rmarkdown` R package as far as I can see and it might well be that this is where the issues begin...

**Comment by martin-ueding** [comment]
I have commented out the bibliography stuff in `master` such that we still get sensible results from Travis CI. Then we can work on this in a separate pull request.
